name: SSH Server Deploy
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SSH Server Deploy
        uses: AbleLincoln/push-to-sftp@v1.0
        with:
            host: ${{ secrets.SERVER_HOST }}
            port: ${{ secrets.SERVER_PORT }}
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}
            sourceDir: .
            targetDir: /home/jeremym/public_html/no-key
